name: "health-checker-prod"
services:
  backend:
    image: skullyfox/backend:latest
    command: sh -c "npm run migration:up && npm run build && npm run prod"
    env_file: .env
    restart: always
    expose:
      - 4000
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000/'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 20

  frontend:
    container_name: frontend
    image: skullyfox/backend:latest
    command: npm run build
    env_file: .env
    volumes:
      - web-client-build:/app/dist
    restart: always
    depends_on:
      backend:
        condition: service_healthy

  database:
    image: postgres:16
    env_file: .env
    restart: always
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./data/database:/var/lib/postgresql/data

  gateway:
    image: nginx
    ports:
      - 7000:80
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  web-client-build: