name: 'health-checker-test'
services:
  backend-test:
    container_name: backend-test
    build: ./back
    command: sh -c "npm run seed && npm run test"
    env_file: .env.test
    depends_on:
      database-test:
        condition: service_healthy

  frontend-test:
    container_name: frontend-test
    build: ./front
    command: npm run test
    env_file: .env.test

  database-test:
    container_name: database-test
    image: postgres
    env_file: .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
