name: Backend CI

on:
  push:
    paths:
    - 'back/**'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
      working-directory: back

    - name: Check formatting
      run: npx prettier .
      working-directory: back

  lint:
    needs: format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
      working-directory: back

    - name: Lint
      run: npm run lint
      working-directory: back