name: Build and Publish Docker Images

on:
    push:
        branches:
            - main
    # pull_request:
    #     branches:
    #         - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set lowercase repository owner
              id: set_lowercase_owner
              run: echo "::set-output name=repo_owner_lower::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Docker Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Backend image
              uses: docker/build-push-action@v5
              with:
                  context: ./back
                  push: true
                  tags: |
                      ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/backend:latest
                      ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/backend:${{ github.sha }}

            - name: Build and push Frontend image
              uses: docker/build-push-action@v5
              with:
                  context: ./front
                  push: true
                  tags: |
                      ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/frontend:latest
                      ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/frontend:${{ github.sha }}

            - name: Log in to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Tag and push Backend image to DockerHub
              run: |
                  docker pull ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/backend:latest
                  docker tag ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
                  docker tag ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

            - name: Tag and push Frontend image to DockerHub
              run: |
                  docker pull ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/frontend:latest
                  docker tag ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
                  docker tag ghcr.io/${{ steps.set_lowercase_owner.outputs.repo_owner_lower }}/frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
